agent_services: []
search_services: []
analyst_services: []

other_services:
  object_manager: true
  query_manager: true
  semantic_manager: true

sql_statement_permissions:
  - Alter: false
  - Command: true
  - Comment: true
  - Commit: false
  - Create: false
  - Delete: false
  - Describe: true
  - Drop: false
  - Insert: false
  - Merge: false
  - Rollback: true
  - Select: true
  - Transaction: false
  - TruncateTable: false
  - Unknown: false
  - Update: false
  - Use: true
